export POSTGRES_DB=postgres
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_PORT=9920
export POSTGRES_SSL_MODE=disable
export POSTGRES_TIME_ZONE=America/New_York
export PROJECT_NAME=food
